### ISSUE TITLE
configurable dataAttr value

### ISSUE THREAD

**Issue by GeorgeKnap** [olejech/storybook-theme-css-vars#1]
Currently value is either `light` or `dark`. Would it be possible to make it configurable?
My system depends on classes `dark-theme` | `light-theme` and this feature would help me to use this plugin.

**Comment by olejech** [comment]
> Would it be possible to make it configurable?
`.storybook/preview.js`
Sure. You can to set your custom name of themes:
```ts
export const parameters = {
  theme: {
    selector: "body (or your selector with data attribute)",
    dataAttr: "data-theme (or your data attribute)",
    nameLightTheme: "light-theme",
    nameDarkTheme: "dark-theme",
  },
};
```
